apiVersion : apps/v1
kind: Deployment
metadata:
  name: novatecstackakswithdevopsandterraform 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: novatecstackakswithdevopsandterraform
  template:
    metadata:
      labels:
        app: novatecstackakswithdevopsandterraform 
    spec:
      containers:
        - name: novatecstackakswithdevopsandterraform 
          image: bincontainerregstry.azurecr.io/novatecstacktestaksrepos
          ports:
          - containerPort: 8080
