apiVersion: v1
kind: Service
metadata:
    name: novatecstackakswithdevopsandterraform
spec:
    type: LoadBalancer
    ports:
    - port: 8080
    selector:
        app: novatecstackakswithdevopsandterraform
